update object_edit set object_key = "Africa" where object_key = "africanants";
update object_edit set object_key = "Alabama" where object_key = "alabamaants";
update object_edit set object_key = "Alberta" where object_key = "albertaants";
update object_edit set object_key = "Alicante" where object_key = "alicanteants ";
# update object_edit set object_key = "" where object_key = "allantwebants";
update object_edit set object_key = "Andorra" where object_key = "andorraants";
#update object_edit set object_key = "" where object_key = "anomalousants";
update object_edit set object_key = "Arizona" where object_key = "arizonaants";
update object_edit set object_key = "Arkansas" where object_key = "arkansasants";
#update object_edit set object_key = "" where object_key = "atolants";
update object_edit set object_key = "Australia" where object_key = "australianants";
update object_edit set object_key = "Austria" where object_key = "austriaants";
#update object_edit set object_key = "Baja" where object_key = "bajaants";
update object_edit set object_key = "Balearic Islands" where object_key = "balearicislandsants";
update object_edit set object_key = "Barrow Island" where object_key = "barrowislandants";
#update object_edit set object_key = "" where object_key = "bayareaants";
update object_edit set object_key = "Belgium" where object_key = "belgiumants";
update object_edit set object_key = "Bhutan" where object_key = "bhutanants";
update object_edit set object_key = "Borneo" where object_key = "borneoants";
update object_edit set object_key = "Brazil" where object_key = "brazilants";
update object_edit set object_key = "British Columbia" where object_key = "britishcolumbiaants";
update object_edit set object_key = "California" where object_key = "californiaants";
update object_edit set object_key = "Cameroon" where object_key = "cameroonants";
update object_edit set object_key = "China" where object_key = "chinaants";
update object_edit set object_key = "Christmas Island" where object_key = "christmasislandants";
update object_edit set object_key = "Cocos Islands" where object_key = "cocosislandsants";
update object_edit set object_key = "Colorado" where object_key = "coloradoants";
update object_edit set object_key = "Comoros" where object_key = "comorosants";
update object_edit set object_key = "Costa Rica" where object_key = "costaricaants";
update object_edit set object_key = "Crete" where object_key = "creteants";
update object_edit set object_key = "Croatia" where object_key = "croatiaants";
update object_edit set object_key = "Czech Republic" where object_key = "czechrepublicants";
update object_edit set object_key = "Ecuador" where object_key = "ecuadorants";
#update object_edit set object_key = "" where object_key = "edibleants";
#update object_edit set object_key = "" where object_key = "eurasianants";
update object_edit set object_key = "Europa Island" where object_key = "europaislandants";
update object_edit set object_key = "Falkland Islands" where object_key = "falklandislandsants";
update object_edit set object_key = "Faroe Islands" where object_key = "faroeislandsants";
update object_edit set object_key = "Fiji" where object_key = "fijiants";
update object_edit set object_key = "Florida" where object_key = "floridaants";
#update object_edit set object_key = "" where object_key = "floridakeysants";
# update object_edit set object_key = "" where object_key = "fossilants";
update object_edit set object_key = "France" where object_key = "franceants";
update object_edit set object_key = "French Polynesia" where object_key = "frenchpolynesiaants";
update object_edit set object_key = "Galapagos Islands" where object_key = "galapagosislandsants";
update object_edit set object_key = "Georgia" where object_key = "georgiaants";
update object_edit set object_key = "Greece" where object_key = "greeceants";
update object_edit set object_key = "Hawaii" where object_key = "hawaiiants";
update object_edit set object_key = "Illinois" where object_key = "illinoisants";
update object_edit set object_key = "India" where object_key = "indiaants";
# update object_edit set object_key = "" where object_key = "introducedants";
update object_edit set object_key = "" where object_key = "iranants";
update object_edit set object_key = "Italy" where object_key = "italyants";
update object_edit set object_key = "Kenya" where object_key = "kenyaants";
update object_edit set object_key = "Kerguelen Islands" where object_key = "kerguelenislandsants";
update object_edit set object_key = "Krakatau Islands" where object_key = "krakatauislandsants";
update object_edit set object_key = "Laos" where object_key = "laosants";
update object_edit set object_key = "Libya" where object_key = "libyaants";
update object_edit set object_key = "Lord Howe Island" where object_key = "lordhoweislandants";
update object_edit set object_key = "Louisiana" where object_key = "louisianaants";
update object_edit set object_key = "Macaronesia" where object_key = "macaronesiaants";
update object_edit set object_key = "Madagascar" where object_key = "madagascarants";
# update object_edit set object_key = "" where object_key = "malagasyants";
update object_edit set object_key = "Martinique" where object_key = "martiniqueants";
update object_edit set object_key = "Mato Grosso do Sul" where object_key = "matogrossodosulants";
update object_edit set object_key = "Mauritius" where object_key = "mauritiusants";
update object_edit set object_key = "Mayotte" where object_key = "mayotteants";
update object_edit set object_key = "Mexico" where object_key = "mexicoants";
update object_edit set object_key = "Micronesia" where object_key = "micronesiaants";
update object_edit set object_key = "Mississippi" where object_key = "mississippiants";
update object_edit set object_key = "Missouri" where object_key = "missouriants";
update object_edit set object_key = "Myanmar" where object_key = "myanmarants";
# update object_edit set object_key = "" where object_key = "nearcticants";
# update object_edit set object_key = "" where object_key = "neotropicalants";
update object_edit set object_key = "Nepal" where object_key = "nepalants";
update object_edit set object_key = "Netherlands" where object_key = "netherlandsants";
update object_edit set object_key = "New Guinea" where object_key = "newguineaants";
update object_edit set object_key = "New Mexico" where object_key = "newmexicoants";
update object_edit set object_key = "New Zealand" where object_key = "newzealandants";
update object_edit set object_key = "Nicobar Island" where object_key = "nicobarislandants";
update object_edit set object_key = "North Carolina" where object_key = "northcarolinaants";
update object_edit set object_key = "Ohio" where object_key = "ohioants";
update object_edit set object_key = "Pakistan" where object_key = "pakistanants";
update object_edit set object_key = "Palestine" where object_key = "palestineants";
update object_edit set object_key = "Paraguay" where object_key = "paraguayants";
update object_edit set object_key = "Pennsylvania" where object_key = "pennsylvaniaants";
update object_edit set object_key = "Philippines" where object_key = "philippinesants";
# update object_edit set object_key = "" where object_key = "poeants";
update object_edit set object_key = "Queensland" where object_key = "queenslandants";
# update object_edit set object_key = "" where object_key = "redlistants";
# update object_edit set object_key = "" where object_key = "reunionants";
update object_edit set object_key = "Russia" where object_key = "russiaants";
update object_edit set object_key = "Saint Martin" where object_key = "saintmartinants";
update object_edit set object_key = "Saint Vincent and the Grenadines" where object_key = "saintvincentandthegrenadinesants";
update object_edit set object_key = "Saudi Arabia" where object_key = "saudiarabiaants";
update object_edit set object_key = "Serbia" where object_key = "serbiaants";
update object_edit set object_key = "Seychelles" where object_key = "seychellesants";
update object_edit set object_key = "Slovenia" where object_key = "sloveniaants";
update object_edit set object_key = "Solomon Islands" where object_key = "solomonislandsants";
update object_edit set object_key = "South Carolina" where object_key = "southcarolinaants";
update object_edit set object_key = "South Korea" where object_key = "southkoreaants";
update object_edit set object_key = "Sri Lanka" where object_key = "srilankaants";
update object_edit set object_key = "Syria" where object_key = "syriaants";
update object_edit set object_key = "Tanzania" where object_key = "tanzaniaants";
update object_edit set object_key = "Tennessee" where object_key = "tennesseeants";
update object_edit set object_key = "Texas" where object_key = "texasants";
update object_edit set object_key = "Tokelau" where object_key = "tokelauants";
update object_edit set object_key = "United Arab Emirates" where object_key = "unitedarabemiratesants";
update object_edit set object_key = "United Kingdom" where object_key = "unitedkingdomants";
update object_edit set object_key = "Utah" where object_key = "utahants";
# update object_edit set object_key = "" where object_key = "westernaustraliaants";
# update object_edit set object_key = "" where object_key = "worldants";
update object_edit set object_key = "Xishuangbanna" where object_key = "xishuangbannaants";

update object_hist set object_key = "India" where object_key = "indiaants";
update object_hist set object_key = "Sri Lanka" where object_key = "srilankaants";
update object_hist set object_key = "Bhutan" where object_key = "bhutanants";
update object_hist set object_key = "Pakistan" where object_key = "pakistanants";
update object_hist set object_key = "Nepal" where object_key = "nepalants";
update object_hist set object_key = "Ohio" where object_key = "ohioants";


