version: "3.9"

services:
  antweb:
    build:
      args:
        ENV: DEV

    ports:
      - "9090:9090"

    environment:
      JAVA_OPTS: "$JAVA_OPTS -Dcom.sun.management.jmxremote.rmi.port=9090 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=localhost"
    volumes:
      - ".:/antweb/deploy"
      # These files are normally copied to final folder, since ant deploy doesn't follow symlinks
      # We link them using bind mounts instead so they can be modified without rebuilding the container
      - ./etc/AppResDevDocker.properties:/usr/local/antweb/WEB-INF/classes/AntwebResources.properties
      - ./etc/log4jAntweb.properties:/usr/local/antweb/WEB-INF/classes/log4j.properties
      - ./WEB-INF/struts-configDbAnt.xml:/usr/local/antweb/WEB-INF/struts-configDb.xml

  api:
    volumes:
      - "./api/v3.1:/api"   # Mount the api dir in the container for making edits without rebuilding
    ports:
    - "127.0.0.1:5000:5000"   #Expose the api outside the container to the local machine for debugging
    command: ["--reload"]


  httpd:
    environment:
      ENV: 'DEV'
      image_bucket_url: "https://slevin.calacademy.org:9000/antweb"