.idea/
.git/
api/
database/
logs/

web/web/*
!web/web/bak
!web/web/homepage
!web/web/image
!web/web/team
!web/web/imageUploader


.dockerignore
.gitignore
docker-compose.yml
README.md

# Ignore sql dumps
*.sql.gz
