#
# Execute as such:
#  mysql -u antweb -p ant < db/upgrade/4.57/2012-02-25.sql
#

alter table taxon add column kingdom_name varchar(64), add column phylum_name varchar(64), add column class_name varchar(64), add column order_name varchar(64);

alter table specimen add column kingdom_name varchar(64), add column phylum_name varchar(64), add column class_name varchar(64), add column order_name varchar(64), modify habitat varchar(256);

CREATE TABLE `taxon` (
  `taxon_name` varchar(128) NOT NULL,
  `rank` varchar(16) NOT NULL,
  `kingdom_name` varchar(64) DEFAULT NULL,
  `phylum_name` varchar(64) DEFAULT NULL,
  `class_name` varchar(64) DEFAULT NULL,
  `order_name` varchar(64) DEFAULT NULL,
  `family` varchar(65) DEFAULT 'formicidae',
  `subfamily` varchar(64) DEFAULT NULL,
  `tribe` varchar(64) DEFAULT NULL,
  `genus` varchar(64) DEFAULT NULL,
  `subgenus` varchar(64) DEFAULT NULL,
  `speciesgroup` varchar(64) DEFAULT NULL,
  `species` varchar(64) DEFAULT NULL,
  `subspecies` varchar(64) DEFAULT NULL,
  `parent` varchar(128) DEFAULT NULL,
  `valid` int(11) DEFAULT NULL,
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `fossil` tinyint(4) DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `source` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`taxon_name`),
  UNIQUE KEY `id` (`id`),
  KEY `genus_species` (`genus`,`species`),
  KEY `subfamily` (`subfamily`),
  KEY `genus` (`genus`),
  KEY `species` (`species`),
  KEY `subfamily_genus_species` (`subfamily`,`genus`,`species`)
) ENGINE=InnoDB AUTO_INCREMENT=701349 DEFAULT CHARSET=utf8
;

CREATE TABLE `specimen` (
  `code` varchar(128) NOT NULL,
  `taxon_name` varchar(128) DEFAULT NULL,
  `kingdom_name` varchar(64) DEFAULT NULL,
  `phylum_name` varchar(64) DEFAULT NULL,
  `class_name` varchar(64) DEFAULT NULL,
  `order_name` varchar(64) DEFAULT NULL,
  `family` varchar(65) DEFAULT 'formicidae',
  `subfamily` varchar(64) DEFAULT NULL,
  `tribe` varchar(64) DEFAULT NULL,
  `genus` varchar(64) DEFAULT NULL,
  `subgenus` varchar(64) DEFAULT NULL,
  `speciesgroup` varchar(64) DEFAULT NULL,
  `species` varchar(64) DEFAULT NULL,
  `subspecies` varchar(64) DEFAULT NULL,
  `other` longtext,
  `type` varchar(64) DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `adm2` varchar(128) DEFAULT NULL,
  `adm1` varchar(128) DEFAULT NULL,
  `localityname` text,
  `localitycode` varchar(128) DEFAULT NULL,
  `collectioncode` varchar(128) DEFAULT NULL,
  `biogeographicregion` varchar(64) DEFAULT NULL,
  `decimal_latitude` float DEFAULT NULL,
  `decimal_longitude` float DEFAULT NULL,
  `last_modified` datetime DEFAULT NULL,
  `habitat` varchar(256) DEFAULT NULL,
  `method` varchar(256) DEFAULT NULL,
  `toc` varchar(128) DEFAULT NULL,
  `ownedby` varchar(128) DEFAULT NULL,
  `collectedby` varchar(128) DEFAULT NULL,
  `caste` varchar(128) DEFAULT NULL,
  `access_group` int(11) DEFAULT NULL,
  `locatedat` varchar(128) DEFAULT NULL,
  `determinedby` varchar(80) DEFAULT NULL,
  `medium` varchar(80) DEFAULT NULL,
  `spcmrecorddate` datetime DEFAULT NULL,
  `spcmrecchangeddate` datetime DEFAULT NULL,
  `locrecorddate` datetime DEFAULT NULL,
  `locrecchangeddate` datetime DEFAULT NULL,
  `speciesauthor` varchar(80) DEFAULT NULL,
  `access_login` int(11) DEFAULT NULL,
  `elevation` int(11) DEFAULT NULL,
  `date_collected` date DEFAULT NULL,
  `latlonmaxerror` varchar(128) DEFAULT NULL,
  `microhabitat` varchar(256) DEFAULT NULL,
  `datedetermined` date DEFAULT NULL,
  `elevationmaxerror` varchar(128) DEFAULT NULL,
  `localitynotes` text,
  `dnaextractionnotes` varchar(256) DEFAULT NULL,
  `specimennotes` text,
  `datescollected` varchar(128) DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `collectionnotes` text,
  `datecollectedstart` date DEFAULT NULL,
  `datecollectedend` date DEFAULT NULL,
  `datecollectedstartstr` varchar(20) DEFAULT NULL,
  `datecollectedendstr` varchar(20) DEFAULT NULL,
  `datedeterminedstr` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`code`),
  KEY `genus_species_idx` (`genus`,`species`),
  KEY `IX_specimen` (`code`),
  KEY `code_type` (`code`,`type`),
  KEY `specimen_taxon_name` (`taxon_name`),
  KEY `subfamily` (`subfamily`),
  KEY `loc_code_idx` (`localitycode`),
  KEY `county_idx` (`adm2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 

