---
name: Bug Report
about: Report a bug or unexpected behavior in AntWeb
title: '[BUG] '
labels: bug
assignees: ''
---

## Bug Description

A clear and concise description of what the bug is.

## Steps to Reproduce

1. Go to '...'
2. Click on '...'
3. Upload file '...'
4. See error

## Expected Behavior

What you expected to happen.

## Actual Behavior

What actually happened.

## Error Messages

```
Paste any error messages here
```

## Environment

- **AntWeb Version:** (e.g., 9.0.0)
- **Browser:** (e.g., Chrome 120, Firefox 121, Safari 17)
- **Operating System:** (e.g., macOS 14, Windows 11, Ubuntu 22.04)
- **Device:** (e.g., Desktop, Mobile)

## File Details (if applicable)

- **File Type:** (e.g., specimen.txt, images.zip)
- **File Size:** (e.g., 2.5 MB)
- **File Format:** (e.g., tab-delimited, CSV)
- **Sample Data:** (first few lines if possible)

## Screenshots

If applicable, add screenshots to help explain the problem.

## Server Logs (if available)

```
Paste relevant server logs here
```

## Related Issues

- Related to #(issue number)
- Possibly caused by #(issue number)

## Additional Context

Any other context about the problem.

## Possible Solution (optional)

If you have suggestions on how to fix this.
