---
name: Feature Request
about: Suggest a new feature or enhancement for AntWeb
title: '[FEATURE] '
labels: enhancement
assignees: ''
---

## Feature Description

A clear and concise description of the feature you'd like to see.

## Problem or Use Case

What problem does this feature solve? What use case does it address?

**Example:** "As a researcher, I need to be able to export specimen data in Darwin Core format so that I can share data with other institutions."

## Proposed Solution

Describe how you envision this feature working.

## Alternative Solutions

Have you considered any alternative solutions or features?

## Benefits

Who would benefit from this feature and how?

- Researchers: ...
- Curators: ...
- Public users: ...
- Developers: ...

## Implementation Considerations

**Complexity:** (Low / Medium / High)

**Roadmap Alignment:** Which phase of the [development roadmap](https://github.com/calacademy-research/antweb/blob/master/docs/ROADMAP.md) does this fit into?

- Phase 1 (Security & Foundation)
- Phase 2 (API)
- Phase 3 (Frontend)
- Phase 4 (Backend)
- Future / Not aligned

**Dependencies:** What other features or changes does this depend on?

## Mockups or Examples (optional)

If applicable, add mockups, wireframes, or examples from other applications.

## Additional Context

Any other context, screenshots, or information about the feature request.

## Related Issues

- Related to #(issue number)
- Builds on #(issue number)
