---
name: Security Vulnerability
about: Report a security vulnerability (PRIVATE - do not use for sensitive issues)
title: '[SECURITY] '
labels: security
assignees: ''
---

## ⚠️ IMPORTANT - READ FIRST

**For sensitive security issues:** Do NOT create a public issue. Instead, email security details privately to: bpescador@gmail.com

**Only use this template for:**
- Known CVEs in dependencies (already public)
- Security improvements or hardening suggestions
- Non-sensitive security questions

---

## Security Issue Description

Clear description of the security concern.

## Issue Type

- [ ] Known CVE in dependency
- [ ] Security hardening suggestion
- [ ] Security configuration issue
- [ ] Other (describe below)

## Affected Component

- [ ] Authentication system
- [ ] API endpoints
- [ ] Database
- [ ] File upload
- [ ] Dependencies
- [ ] Configuration
- [ ] Other: ___________

## Severity Assessment

**Your assessment:** (Critical / High / Medium / Low)

## Details

### CVE Information (if applicable)
- **CVE ID:** CVE-YYYY-XXXXX
- **Affected Package:** package-name version X.Y.Z
- **Fixed in Version:** X.Y.Z
- **CVSS Score:** X.X

### Description
Detailed description of the vulnerability or security concern.

### Affected Versions
Which versions of AntWeb are affected?

### Proof of Concept (if safe to share)
```
Include safe demonstration if applicable
```

## Recommended Fix

What steps should be taken to address this?

## References

- Link to CVE database
- Link to vendor advisory
- Link to patch or fix

## Roadmap Alignment

This aligns with Phase 1 (Security & Foundation) of the [development roadmap](https://github.com/calacademy-research/antweb/blob/master/docs/ROADMAP.md).

## Additional Context

Any other relevant information.

---

**Note:** Security issues are tracked as part of [Phase 1: Security & Foundation](https://github.com/calacademy-research/antweb/blob/master/docs/PHASE1.md).
