# From within the web/speciesList/ directory, execute:
#
#   sh antweb/src/sh/moveProjectTxt.sh
#

mv ./mayotte/mayotteants_project.txt ./mayotte/mayotteants_speciesList.txt
mv ./fossil/fossilants_project.txt ./fossil/fossilants_speciesList.txt
mv ./serbia/serbiaants_project.txt ./serbia/serbiaants_speciesList.txt
mv ./galapagos/galapagosants_project.txt ./galapagos/galapagosants_speciesList.txt
mv ./seychelles/seychellesants_project.txt ./seychelles/seychellesants_speciesList.txt
mv ./slovenia/sloveniaants_project.txt ./slovenia/sloveniaants_speciesList.txt
mv ./belgium/belgiumants_project.txt ./belgium/belgiumants_speciesList.txt
mv ./reunion/reunionants_project.txt ./reunion/reunionants_speciesList.txt
mv ./arkansas/arkansasants_project.txt ./arkansas/arkansasants_speciesList.txt
mv ./croatia/croatiaants_project.txt ./croatia/croatiaants_speciesList.txt
mv ./macaronesia/macaronesiaants_project.txt ./macaronesia/macaronesiaants_speciesList.txt
mv ./atol/atolants_project.txt ./atol/atolants_speciesList.txt
mv ./austria/austriaants_project.txt ./austria/austriaants_speciesList.txt
mv ./utah/utahants_project.txt ./utah/utahants_speciesList.txt
mv ./matogrossodosul/matogrossodosulants_project.txt ./matogrossodosul/matogrossodosulants_speciesList.txt
mv ./madagascar/madants_project.txt ./madagascar/madants_speciesList.txt
mv ./solomons/solomonsants_project.txt ./solomons/solomonsants_speciesList.txt
mv ./borneo/borneoants_project.txt ./borneo/borneoants_speciesList.txt
mv ./paraguay/paraguayants_project.txt ./paraguay/paraguayants_speciesList.txt
mv ./arizona/arizonaants_project.txt ./arizona/arizonaants_speciesList.txt
mv ./alicante/alicanteants_project.txt ./alicante/alicanteants_speciesList.txt
mv ./fiji/fijiants_project.txt ./fiji/fijiants_speciesList.txt
mv ./georgia/georgiaants_project.txt ./georgia/georgiaants_speciesList.txt
mv ./illinois/illinoisants_project.txt ./illinois/illinoisants_speciesList.txt
mv ./alabama/alabamaants_project.txt ./alabama/alabamaants_speciesList.txt
mv ./mauritius/mauritiusants_project.txt ./mauritius/mauritiusants_speciesList.txt
mv ./alberta/albertaants_project.txt ./alberta/albertaants_speciesList.txt
mv ./florida/floridaants_project.txt ./florida/floridaants_speciesList.txt
mv ./india/indiaants_project.txt ./india/indiaants_speciesList.txt
mv ./newzealand/newzealandants_project.txt ./newzealand/newzealandants_speciesList.txt
mv ./philippines/philippinesants_project.txt ./philippines/philippinesants_speciesList.txt
mv ./micronesia/micronesiaants_project.txt ./micronesia/micronesiaants_speciesList.txt
mv ./tokelau/tokelauants_project.txt ./tokelau/tokelauants_speciesList.txt
mv ./iran/iranants_project.txt ./iran/iranants_speciesList.txt
mv ./france/franceants_project.txt ./france/franceants_speciesList.txt
mv ./hawaii/hawaiiants_project.txt ./hawaii/hawaiiants_speciesList.txt
mv ./introduced/introducedants_project.txt ./introduced/introducedants_speciesList.txt
mv ./frenchpolynesia/frenchpolynesiaants_project.txt ./frenchpolynesia/frenchpolynesiaants_speciesList.txt
mv ./poe/poeants_project.txt ./poe/poeants_speciesList.txt
mv ./baja/bajaants_project.txt ./baja/bajaants_speciesList.txt
mv ./newguinea/newguineaants_project.txt ./newguinea/newguineaants_speciesList.txt
mv ./world/worldants_project.txt ./world/worldants_speciesList.txt
mv ./texas/texasants_project.txt ./texas/texasants_speciesList.txt
mv ./italy/italyants_project.txt ./italy/italyants_speciesList.txt
mv ./ohio/ohioants_project.txt ./ohio/ohioants_speciesList.txt
mv ./malagasy/malagasyants_project.txt ./malagasy/malagasyants_speciesList.txt
mv ./mississippi/mississippiants_project.txt ./mississippi/mississippiants_speciesList.txt
mv ./china/chinaants_project.txt ./china/chinaants_speciesList.txt
mv ./comoros/comorosants_project.txt ./comoros/comorosants_speciesList.txt
mv ./saudi/saudiants_project.txt ./saudi/saudiants_speciesList.txt
mv ./floridakeys/floridakeysants_project.txt ./floridakeys/floridakeysants_speciesList.txt
mv ./california/calants_project.txt ./california/calants_speciesList.txt
mv ./queensland/queenslandants_project.txt ./queensland/queenslandants_speciesList.txt
mv ./bayarea/bayareaants_project.txt ./bayarea/bayareaants_speciesList.txt
mv ./greece/greeceants_project.txt ./greece/greeceants_speciesList.txt
mv ./anomalous/anomalousants_project.txt ./anomalous/anomalousants_speciesList.txt
mv ./northcarolina/northcarolinaants_project.txt ./northcarolina/northcarolinaants_speciesList.txt
mv ./southcarolina/southcarolinaants_project.txt ./southcarolina/southcarolinaants_speciesList.txt
mv ./costarica/costaricaants_project.txt ./costarica/costaricaants_speciesList.txt
mv ./uae/uaeants_project.txt ./uae/uaeants_speciesList.txt
mv ./louisiana/louisianaants_project.txt ./louisiana/louisianaants_speciesList.txt
mv ./czech/czechants_project.txt ./czech/czechants_speciesList.txt
mv ./newmexico/newmexicoants_project.txt ./newmexico/newmexicoants_speciesList.txt
mv ./tennessee/tennesseeants_project.txt ./tennessee/tennesseeants_speciesList.txt
mv ./kenya/kenyaants_project.txt ./kenya/kenyaants_speciesList.txt
mv ./pennsylvania/pennsylvaniaants_project.txt ./pennsylvania/pennsylvaniaants_speciesList.txt
mv ./colorado/coloradoants_project.txt ./colorado/coloradoants_speciesList.txt
mv ./netherlands/netherlandsants_project.txt ./netherlands/netherlandsants_speciesList.txt
mv ./missouri/missouriants_project.txt ./missouri/missouriants_speciesList.txt
mv ./britishcolumbia/britishcolumbiaants_project.txt ./britishcolumbia/britishcolumbiaants_speciesList.txt
